/** Declaration file generated by dts-gen */

export = level;

declare function level(location: any, options: any, callback?: any): any;

declare namespace level {

    function destroy(location: any, callback: any): void;

    function repair(location: any, callback: any): void;

    namespace destroy {
    }

    namespace errors {
        class EncodingError {
            constructor(message: any, cause: any);

        }

        class InitializationError {
            constructor(message: any, cause: any);

        }

        class LevelUPError {
            constructor(message: any, cause: any);

        }

        class NotFoundError {
            constructor(message: any, cause: any);

        }

        class OpenError {
            constructor(message: any, cause: any);

        }

        class ReadError {
            constructor(message: any, cause: any);

        }

        class WriteError {
            constructor(message: any, cause: any);

        }

        namespace EncodingError {
            const cause: any;

            const message: any;

            const name: string;

            const stack: string;

            const type: string;

            function toString(): any;
        }

        namespace InitializationError {
            const cause: any;

            const message: any;

            const name: string;

            const stack: string;

            const type: string;

            function toString(): any;
        }

        namespace LevelUPError {
            const cause: any;

            const message: any;

            const name: string;

            const stack: string;

            const type: string;

            function toString(): any;
        }

        namespace NotFoundError {
            const cause: any;

            const message: any;

            const name: string;

            const notFound: boolean;

            const stack: string;

            const status: number;

            const type: string;

            function toString(): any;
        }

        namespace OpenError {
            const cause: any;

            const message: any;

            const name: string;

            const stack: string;

            const type: string;

            function toString(): any;
        }

        namespace ReadError {
            const cause: any;

            const message: any;

            const name: string;

            const stack: string;

            const type: string;

            function toString(): any;
        }

        namespace WriteError {
            const cause: any;

            const message: any;

            const name: string;

            const stack: string;

            const type: string;

            function toString(): any;

        }

    }

    namespace repair {
    }

}

